title = "有卖网"
baseURL = "http://www.th2w.com/"
nguageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "工作"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "博客"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "服务"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "联系"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "关于我们"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "联系我们"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "运作方式"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "博客"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "协议条款"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2018"

  home = "首页"

  [params.slider]
    enable = true
    title = "数字营销 &amp; 设计机构 "
    subtitle = "我们热爱网络和我们所做的工作。<br/>我们与客户紧密合作，为客户提供最佳的解决方案"

  [params.wrapper]
    enable = true
    title = "关于我们"
    italic = "在遥远的地方，在“山”这个词的后面，在远离“Vokalia”和“Consonantia”的地方，存在着“盲文”。他们住在位于语义学海岸的Bookmarksgrove。"
    paragraph = "上帝保佑我们，上帝保佑我们，上帝保佑我们。但是，如果你的工作是你的工作，那么你的工作就会变得很好。在我们的国家里，有许多人都是欧洲人。除了不能证明的错误之外，在这个错误的错误中，我们应该承认"

  [params.blog]
    enable = true
    title = "了解我们的最新进展"
    subtitle = "随时随地赶上我们"

  [params.feature]
    enable = true
    title = "我们相信伟大的思想"
    content = "在每一个人年轻时，都会有很多诸如让生命变得有意义，让生命充满光辉的信念，但是随着岁月流转，这些信念大多在中年冷漠的人生观里丧失殆尽。但于我而畜，至少还有一样留存了下来，并和从前一样明亮，一样令我感到充实和满足，那就是对英雄毫无顾忌的崇拜。"
    [params.feature.button]
      caption = "查看工作"
      url = "#"

  [params.call]
    enable = true
    title = "我们设计令人愉快的数字体验。"
    paragraph = "多了解我们的工作和设计理念。你自己来判断我们为其他客户所做的工作和取得的成果，然后去见我们的团队，这个团队经验丰富，热爱设计。"

  [params.contact]
    enable = true
    title = "给我们留言"
    subtitle = "不要只相信我们的话。看看我们最新的作品。"
    [params.contact.form]
      name = "姓名"
      email = "邮箱"
      subject = "主题"
      message = "信息"
      button = "发送"
    [params.contact.box]
      title = "顺便来看看"
      address = "北京海淀区"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "我们也在谷歌映射中计数"
